Update Traditional Chinese (zh_tw.json)
TheCSMods/mc-better-stats pull request #129
Opened 2024-07-07 06:57 UTC by yichifauzi

fix so many typo still need notlin4 to proofreading
Do not merge yet! Please wait for @notlin4's review before merging.

2024-07-07 08:32 UTC, notlin4 requested changes

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
>  	"betterstats.config.register_commands": "註冊指令",
```suggestion
	"betterstats.config.register_commands": "登錄指令",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.hud_screen.tutorial_1": "對統計資訊點選右鍵（[Shift] + 右鍵）將其新增至此處。",
```suggestion
	"betterstats.gui.hud_screen.tutorial_1": "對統計資訊按下右鍵（[Shift] + 右鍵）將其新增至這裡。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.hud_screen.tutorial_2": "對 HUD 項目點選右鍵以進行修改或移除。",
```suggestion
	"betterstats.gui.hud_screen.tutorial_2": "在 HUD 項目上按下右鍵以進行修改或移除。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
>  	"betterstats.gui.hud_screen.tutorial_3": "按下 Esc 鍵以關閉此畫面。",
```suggestion
	"betterstats.gui.hud_screen.tutorial_3": "按下 Esc 以關閉這個畫面。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
>  	"betterstats.network.betterstatsnetworkhandler.consent_warning": "重要：\n啟用此功能後，伺服器將會發現您正在使用安裝了「betterstats」的修改用戶端。為了保護您的隱私，請勿在可能不允許修改用戶端或此模組的伺服器上使用此功能。\n\n啟用此功能會新增一些額外功能，這些功能僅在模組也安裝在伺服器上時可用。",
```suggestion
	"betterstats.network.betterstatsnetworkhandler.consent_warning": "重要事項：\n啟用這項功能後，伺服器將知道你使用的是安裝了「betterstats」的模組用戶端。為保護你的隱私，請勿在可能不允許模組用戶端或這個模組的伺服器上使用這項功能。\n\n啟用這項功能後，如果伺服器也安裝了該模組，將有額外功能可用。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.tpsbs.tab.ssps.description": "允許您瀏覽當前連接的伺服器上存在的玩家，並從伺服器請求他們的統計資訊。",
```suggestion
	"betterstats.gui.tpsbs.tab.ssps.description": "讓你瀏覽目前伺服器上的玩家，並請求伺服器提供他們的統計資訊。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.tpsbs.tab.ssps.player_not_found": "伺服器找不到您請求的玩家名稱。\n\n請確保在重試之前符合以下條件：\n1. 確保名稱拼字和大小寫正確\n2. 請求的玩家在線上\n3. 請求的玩家安裝了此模組\n4. 請求的玩家在其模組設定中啟用了「允許統計資訊分享」",
```suggestion
	"betterstats.gui.tpsbs.tab.ssps.player_not_found": "伺服器找不到你請求的玩家名稱。\n\n請確保滿足下列條件後再重試：\n1. 名稱拼字和大小寫正確\n2. 請求的玩家在線上\n3. 請求的玩家已安裝這個模組\n4. 請求的玩家已在這個模組的設置中啟用「統計資訊分享」",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.tpsbs.tab.qs.description": "僅需點選一個按鈕，即可快速與使用此模組的任何人分享您的統計資訊，無論他們現在身在何處。",
```suggestion
	"betterstats.gui.tpsbs.tab.qs.description": "只需點選一個按鈕，即可快速與使用這個模組的任何人分享你的統計資訊，無論他們身在何處。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.tpsbs.tab.qs.tos_notice": "快速分享是一個利用我（模組開發者）的伺服器運作的功能。因此，它適用於我的服務條款和隱私權政策。",
```suggestion
	"betterstats.gui.tpsbs.tab.qs.tos_notice": "快速分享功能使用我的（模組開發者的）伺服器。因此，需要遵守我的《服務條款》和《隱私權政策》。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.tpsbs.tab.qs.abuse_notice": "為防止垃圾訊息和濫用，可能會適用速率限制和其他限制。",
```suggestion
	"betterstats.gui.tpsbs.tab.qs.abuse_notice": "為防止垃圾訊息和濫用，可能會有速率限制以及其他限制。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.tpsbs.tab.qs.step_1": "§e第一步：\n§7點選按鈕快速分享您當前查看的統計檔案。分享完成後，您將獲得一個「快速分享代碼」。",
```suggestion
	"betterstats.gui.tpsbs.tab.qs.step_1": "§e第一步：\n§7點選按鈕快速分享你目前查看的統計檔案。之後，會上傳統計資訊，你會取得「快速分享碼」。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
> +	"betterstats.gui.tpsbs.tab.qs.step_2": "§e第二步：\n§7接收方輸入「快速分享代碼」，並點選按鈕下載和查看分享的統計資訊。",
```suggestion
	"betterstats.gui.tpsbs.tab.qs.step_2": "§e第二步：\n§7需要查看共享統計資訊的人輸入「快速分享碼」，然後點選按鈕下載並查看共用的統計資訊。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
>  	"betterstats.gui.tpsbs.tab.qs.step_2.enter_qscode": "在此輸入快速分享代碼",
```suggestion
	"betterstats.gui.tpsbs.tab.qs.step_2.enter_qscode": "在這裡輸入快速分享碼",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
>  	"betterstats.sas.first_death.hc1": "%s 剛剛死亡了，這是他們的第一次。好消息是，這可能不會再次發生。",
```suggestion
	"betterstats.sas.first_death.hc1": "%s 剛剛第一次死亡。好消息是，這可能不會再次發生。",

```

2024-07-07 08:32 UTC, notlin4 commented on betterstats-3-fabric-1.21/src/main/resources/assets/betterstats/lang/zh_tw.json
>  	"betterstats.gui.tpsbs.tab.ssps.requirements": "此功能要求您和伺服器都安裝了最新（或更好是相同）版本的此模組。",
```suggestion
	"betterstats.gui.tpsbs.tab.ssps.requirements": "這項功能要求你和伺服器都安裝了這個模組的最新版本（或更好是相同版本）。",

```

2024-07-09 16:08 UTC, notlin4 approved these changes

2024-07-12 07:38 UTC, TheCSDev commented
Amazing. Thank you so much to both of you. Will merge now and likely publish an update later today.

2024-07-12 07:38 UTC, merged